gitRepoUrl = "https://github.com/nek-technology/AnimaLib"
gitSourceBranch = "main"
changelog = true

[home]
enabled = true
includeReadme = false

[docusaurus]
tagline = "An animation module used to streamline animation tasks."
favicon = "/favicon.png"
