[package]
name = "nek-technology/animalib"
description = "An animation module used to streamline animation tasks."
version = "0.2.3"
license = "lgpl-3.0"
registry = "https://github.com/UpliftGames/wally-index"
homepage = "https://nek-technology.github.io/AnimaLib/"
repo =  "https://github.com/nek-technology/animalib"
realm = "shared"
exclude = ["**"]
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json"]

[dependencies]
Janitor = "howmanysmall/janitor@1.15.6"
