[package]
name = "thebetterdark/animalib"
description = "An animation module used to streamline animation tasks."
version = "0.1.0"
license = "lgpl-3.0"
authors = ["thebetterdark"]
registry = "https://github.com/UpliftGames/wally-index"
repo =  "https://github.com/thebetterdark/animalib"
realm = "shared"
exclude = ["**"]
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json"]