name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup-aftman
        uses: ok-nick/setup-aftman@v0.3.0

      - name: Lint
        run: selene ./src

  style:
    name: Styling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: JohnnyMorganz/stylua-action@v1.1.2
        with:
          token: ${{ SECRETS.GITHUB_TOKEN }}
          args: --check .

  unit-tests:
    name: Unit Tests
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Aftman
        uses: ok-nick/setup-aftman@v0.3.0

      - name: Install Packages
        run: wally install

      - name: Install Roblox Studio
        uses: OrbitalOwen/roblox-win-installer-action@1.1
        with:
          cookie: ${{ secrets.ROBLOSECURITY }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build test place
        run: rojo build test.project.json -o test.rbxl

      - name: Run test
        run: run-in-roblox --place test.rbxl --script tests\\test.server.lua > test-out.txt
        continue-on-error: true
        timeout-minutes: 3
