name: Releases

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      draft:
        type: choice
        description: Is this a draft release?
        options: 
        - true
        - false
      pre-release:
          type: choice
          description: Is this a pre-release?
          options: 
          - true
          - false

jobs: 
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
    
          - name: setup-aftman
            uses: ok-nick/setup-aftman@v0.3.0
    
          - name: Run Stylua
            run: stylua src --check
    
          - name: Run Selene
            run : selene src

          - name: Build animalib.rbxm
            run: rojo build -o animalib.rbxm release.project.json
    
          - name: Upload animalib.rbxm as build artifact
            uses: actions/upload-artifact@v3
            with: 
              name: animalib
              path: animalib.rbxm
    
          - name: Get Release from wally.toml
            uses: SebRollen/toml-action@v1.0.2
            id: read_toml
            with: 
              file: 'wally.toml'
              field: 'package.version'
    
    
          - name: Publish to Wally
            env: 
              WALLY_TOKEN: ${{ secrets.WALLY_AUTH_TOKEN }}
            run: |
              mkdir =p ~/.wally
              printf "[tokens]\n\"https://api.wally.run/\" = \"%s\"" "$WALLY_TOKEN" >> ~/.wally/auth.toml
              wally publish
    
          - name: Release
            uses: softprops/action-gh-release@v0.1.15
            with: 
              name: ${{ steps.read_toml.outputs.value }}
              tag_name: ${{ steps.read_toml.outputs.value }}
              files: animalib.rbxm
              prerelease: ${{ github.event.inputs.pre-release }}
              draft: ${{ github.event.inputs.draft }}